Homework 3
Stassobaka/nodejs24_hw_-YOURNAME- pull request #3
Opened 2024-02-04 22:41 UTC by Stassobaka

2024-02-04 22:45 UTC, Stassobaka commented
Привет. Сразу извиняюсь за код)))  Решил добавить себе для тестов модуль return_directory, но когда залез туда уже не рад был))) С помощью google что то написал, вроде работает. В коментариях указал как работает. Так вроде задание выполнил)))

2024-02-05 09:10 UTC, evhenious commented
Привіт. У тебе в ПР конфлікт, бачив? Зможеш порішати сам?

2024-02-05 09:18 UTC, evhenious commented on return_directory.js
Оце ти перестарався трохи - таке складне рішення замість простого створення пари пустих файліків для тестування... не дуже ця штука потрібна, я б сказав (тим більше вона захардкоджена під Windows і у мене, наприклад, без допилювання працювати не буде). Але раз зробив - хай буде, я в неї не полізу :)

2024-02-05 09:29 UTC, evhenious commented on fileSync.js
Дивись, є проблема. 
1. папка `target` пуста, `source` має отаку стурктуру:
<img width="239" alt="image" src="https://github.com/Stassobaka/nodejs24_hw_-YOURNAME-/assets/5249435/9ac903fb-dc0c-4ec5-96ae-b4d2c047cca6">

Все спрацює ОК.

2. Я йду в папку `target`, видаляю отой внутрішній `secondary.file`. Перезапускаю твій код, очікую що цей видалений файлік має там з'явитись, бо він є в `source` і має скопіюватись після синхронізації. Але він не з'являється:
<img width="239" alt="image" src="https://github.com/Stassobaka/nodejs24_hw_-YOURNAME-/assets/5249435/06ed5b4b-60a6-4f90-9a1f-63e49ccdf687">

Код працює без видимих помилок, значить десь в логіці у тебе є недопрацювання

2024-02-05 09:31 UTC, evhenious requested changes
Розберись будь ласка чому не працює приклад із мого коментаря

2024-02-05 17:51 UTC, Stassobaka commented
Все разобрался.

2024-02-05 18:51 UTC, evhenious commented
ОК, тепер наче працює нормально. Але питання з конфліктом все іще відкрите - сам порішаєш?

2024-02-07 22:10 UTC, Stassobaka commented
Привет. Если будет время можешь посмотреть будут ли у тебя работать другие методы на линукс. домучал вроде)

2024-02-08 13:45 UTC, evhenious commented
> Привет. Если будет время можешь посмотреть будут ли у тебя работать другие методы на линукс. домучал вроде)

Круто, ввечорі сьогодні гляну

2024-02-08 20:07 UTC, evhenious commented
Моя повага, пане! Ви дожали )) все працює. Так, безумовно можна було зробити простіше - але я радий що ти дотиснув сам.
Я трохи допоміг порішати конфлікт в бранчах

2024-02-08 20:07 UTC, merged